Internal Transfer feature.
paritytech/parity-bridges-ui pull request #256
Opened 2021-08-10 14:34 UTC by hbulgarini

Related with #213.

This PR includes the finished v1 of the internal Transfer feature. 

Also i have renamed in the code and in the app the term `Local` by `Internal` which is more aligned with the feature description on the issue #213.

2021-08-10 14:43 UTC, hbulgarini commented
@tomusdrw @goldsteinsveta : I have done a minor change on the design regarding the internal receiver field. I added a companion field below the input similar as what we have now. I saw the need of adding this addiotional field below the input because when the user enters a generic account format ( 42 ss58Prefix ) i think is useful for the user to see the receiver account formatted  with the corresponding chain prefix:

Providing native account:
![Screen Shot 2021-08-10 at 11 34 39](https://user-images.githubusercontent.com/12089572/128887577-40e66d21-76ce-486d-bad5-617b392338eb.png)

Providing generic account:
![Screen Shot 2021-08-10 at 11 34 53](https://user-images.githubusercontent.com/12089572/128887584-f38d4190-3d92-4dde-a8b5-a4a51f35e1b7.png)

2021-08-11 12:58 UTC, wirednkod requested changes

2021-08-12 11:42 UTC, hbulgarini commented on src/components/Sender.tsx
> +    minHeight: '100px'
ok! something like `theme.spacing(10)` ?

2021-08-12 11:45 UTC, hbulgarini commented on src/contexts/GUIContextProvider.tsx
> +  useEffect(() => setBridged(true), [action]);
i'm not sure i'm following your comment. When the action variable is changed, this useEffect is triggered reseting the bridged value to true every time.

2021-08-12 12:02 UTC, hbulgarini commented on src/components/BridgedLocalWrapper.tsx
>    }
cool ... last if misses the isBridged:

`  if (isBridged && !showInternal) return children;`

2021-08-12 12:12 UTC, hbulgarini commented on src/contexts/GUIContextProvider.tsx
> +  useEffect(() => setBridged(true), [action]);
ahhh maybe as the code is inline you cannot read the `[action]` dependency?

```
useEffect(() => {
         setBridged(true)
      }
   ,[action]);
```

2021-08-13 08:55 UTC, wirednkod commented on src/components/Sender.tsx
> +    minHeight: '100px'
Exactly

2021-08-13 09:02 UTC, wirednkod commented on src/contexts/GUIContextProvider.tsx
> +  useEffect(() => setBridged(true), [action]);
No I saw the dependency. It just looks weird that the dependent value is not used inside the useEffect.
Afaiu though you want the setBridge to run only when action changes, right?

2021-08-13 09:08 UTC, wirednkod approved these changes

2021-08-13 12:10 UTC, merged